/**
 * Lifecycle event names. Every stage of the recovery loop emits one of these as
 * the `event` field so a full case can be traced by correlation id, and so the
 * audit trail and dashboards share one vocabulary.
 */
export const Events = {
  // Ingestion
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_REJECTED: 'WEBHOOK_REJECTED',
  WEBHOOK_VERIFIED: 'WEBHOOK_VERIFIED',
  WEBHOOK_DUPLICATE: 'WEBHOOK_DUPLICATE',
  WEBHOOK_ACCEPTED: 'WEBHOOK_ACCEPTED',

  // Cases
  CASE_OPENED: 'CASE_OPENED',

  // Payment state
  PAYMENT_UPSERTED: 'PAYMENT_UPSERTED',
  PAYMENT_STATE_CHANGED: 'PAYMENT_STATE_CHANGED',
  PAYMENT_STATE_REJECTED: 'PAYMENT_STATE_REJECTED',

  // Detection and scoring
  RISK_ASSESSED: 'RISK_ASSESSED',
  RECOVERY_SCORED: 'RECOVERY_SCORED',
  DECISION_EV: 'DECISION_EV',

  // Agent
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_COMPLETED: 'AGENT_COMPLETED',
  AGENT_FAILED: 'AGENT_FAILED',
  AGENT_REJECTED: 'AGENT_REJECTED',
  AGENT_FALLBACK: 'AGENT_FALLBACK',
  INJECTION_BLOCKED: 'INJECTION_BLOCKED',

  // Policy and action
  POLICY_APPROVED: 'POLICY_APPROVED',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  ACTION_STARTED: 'ACTION_STARTED',
  ACTION_EXECUTED: 'ACTION_EXECUTED',
  ACTION_FAILED: 'ACTION_FAILED',
  ACTION_SKIPPED: 'ACTION_SKIPPED',
  LINK_CREATED: 'LINK_CREATED',

  // Outcome
  RECOVERY_ATTRIBUTED: 'RECOVERY_ATTRIBUTED',
  CASE_RECOVERED: 'CASE_RECOVERED',
  CASE_STOPPED: 'CASE_STOPPED',
  CASE_ESCALATED: 'CASE_ESCALATED',
  CASE_COMPLETED: 'CASE_COMPLETED',

  // Manual
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',

  // Lifecycle
  SERVER_STARTED: 'SERVER_STARTED',
  SERVER_SHUTDOWN: 'SERVER_SHUTDOWN',
  RECOVERY_SWEEP: 'RECOVERY_SWEEP',
} as const;

export type EventName = (typeof Events)[keyof typeof Events];
